Repository LambdaTest/test-at-scale, pull requests merged in 2022-06, with the labels that each got.

#171 fix: docker image security vulnerability
  build/nucleus/Dockerfile
Labels: release:minor

#175 support for build cache cleanup
  cmd/synapse/bin.go
  go.mod
  go.sum
  pkg/cron/setup.go
  pkg/errs/synapse.go
  pkg/utils/utils.go
Labels: release:patch

#173 #172: Added retries in API
  .github/workflows/premerge.yml
  cmd/nucleus/bin.go
  go.mod
  go.sum
  pkg/azure/client.go
  pkg/blocktestservice/setup.go
  pkg/blocktestservice/setup_test.go
  pkg/cachemanager/cachemanager.go
  pkg/core/interfaces.go
  pkg/core/lifecycle.go
  pkg/core/models.go
  pkg/global/nucleusconstants.go
  pkg/payloadmanager/setup.go
  pkg/payloadmanager/setup_test.go
  pkg/requestutils/request.go
  pkg/service/coverage/coverage.go
  pkg/service/coverage/coverage_test.go
  pkg/service/teststats/teststats.go
  pkg/service/teststats/teststats_test.go
  pkg/synapse/synapse.go
  pkg/tasconfigmanager/setup.go
  pkg/task/task_test.go
  pkg/testdiscoveryservice/testdiscovery.go
  pkg/testdiscoveryservice/testdiscovery_test.go
  pkg/testexecutionservice/testexecution_test.go
  pkg/utils/utils.go
Labels: release:patch

#177 #176: Normalized CPU Percent to <= 100 %
  go.mod
  pkg/procfs/procfs.go
Labels: release:patch

#169 sudo privileges to container user
  build/nucleus/Dockerfile
Labels: release:patch

#184 Updated docker image to include python
  .github/workflows/pull_request_lint.yml
  build/nucleus/Dockerfile
Labels: release:patch

#185 Revert "sudo privileges to container user"
  build/nucleus/Dockerfile
Labels: release:patch

#187 added error message in jobInfo
  pkg/core/wsproto.go
  pkg/synapse/synapse.go
  pkg/synapse/utils.go
Labels: bug, release:patch

#193 fetch blocklisted and qurantined tests for each task
  pkg/blocktestservice/setup_test.go
  pkg/core/lifecycle.go
  pkg/global/nucleusconstants.go
Labels: release:patch

#191 added support for synapse version
  pkg/core/wsproto.go
  pkg/synapse/synapse.go
Labels: release:patch

#195 fix api retry for offline synapse
  pkg/azure/client.go
  pkg/requestutils/request.go
Labels: bug, release:patch

#205 fix yaml version issue and blocklist regression
  .github/workflows/premerge.yml
  pkg/core/lifecycle.go
  pkg/global/nucleusconstants.go
  pkg/utils/utils.go
Labels: bug, release:patch

#208 Fix for js repos failing due to runners not installed.
  pkg/core/lifecycle.go
Labels: release:patch
