Repository LambdaTest/test-at-scale, pull requests merged in 2022-04, with the labels that each got.

#135 minor ci linting, added issue linting for all branch
  .github/workflows/pull_request_lint.yml
  .github/workflows/release.yml
Labels: release:minor

#139 Test file based splitting feature
  pkg/blocktestservice/setup_test.go
  pkg/core/lifecycle.go
  pkg/core/models.go
  pkg/testdiscoveryservice/testdiscovery.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: enhancement, release:patch

#145 fix cicd to support forked repo
  .github/workflows/pull_request_lint.yml
  .github/workflows/release.yml
Labels: release:minor

#136 changed zip url for github
  pkg/gitmanager/setup.go
  pkg/urlmanager/urlmanager.go
  pkg/urlmanager/urlmanager_test.go
Labels: release:minor

#149 Hotfix/task status
  cmd/nucleus/bin.go
  pkg/core/interfaces.go
  pkg/core/lifecycle.go
  pkg/core/models.go
  pkg/requestutils/request.go
  pkg/task/task.go
  pkg/task/task_test.go
  pkg/testdiscoveryservice/testdiscovery.go
  pkg/testexecutionservice/testexecution.go
  pkg/testexecutionservice/testexecution_test.go
Labels: release:patch

#153 #152: Persisting workspace before discovery
  pkg/core/lifecycle.go
Labels: release:patch
