Repository LambdaTest/test-at-scale, pull requests merged in 2022-07, with the labels that each got.

#215 updated endpoints
  pkg/global/synapseconstants.go
Labels: release:patch

#217 fix pnpm cache issue
  pkg/cachemanager/cachemanager.go
Labels: bug, release:patch

#219 fix smart selection in multiconfig
  pkg/driver/driver_v2.go
  pkg/driver/driver_v2_test.go
Labels: bug, release:patch

#222 Refactored SAS URL API
  .github/workflows/premerge.yml
  Makefile
  README.md
  go.mod
  go.sum
  mocks/AzureClient.go
  mocks/BlockTestService.go
  mocks/Builder.go
  mocks/CacheStore.go
  mocks/CoverageService.go
  mocks/DiffManager.go
  mocks/DockerRunner.go
  mocks/Driver.go
  mocks/ExecutionManager.go
  mocks/GitManager.go
  mocks/ListSubModuleService.go
  mocks/LogWriterStrategy.go
  mocks/Logger.go
  mocks/PayloadManager.go
  mocks/Requests.go
  mocks/SecretParser.go
  mocks/SecretsManager.go
  mocks/SynapseManager.go
  mocks/TASConfigManager.go
  mocks/Task.go
  mocks/TestDiscoveryService.go
  mocks/TestExecutionService.go
  mocks/TestStats.go
  mocks/ZstdCompressor.go
  pkg/azure/client.go
  pkg/blocktestservice/setup.go
  pkg/cachemanager/cachemanager.go
  pkg/command/run_test.go
  pkg/command/script_test.go
  pkg/core/interfaces.go
  pkg/core/models.go
  pkg/core/runner.go
  pkg/driver/driver_v1.go
  pkg/driver/driver_v2.go
  pkg/gitmanager/setup_test.go
  pkg/global/nucleusconstants.go
  pkg/listsubmoduleservice/setup.go
  pkg/logwriter/setup.go
  pkg/logwriter/setup_test.go
  pkg/payloadmanager/setup.go
  pkg/payloadmanager/setup_test.go
  pkg/requestutils/request.go
  pkg/runner/docker/config.go
  pkg/runner/docker/docker.go
  pkg/service/coverage/coverage_test.go
  pkg/tasconfigmanager/setup.go
  pkg/task/task.go
  pkg/testdiscoveryservice/testdiscovery.go
  pkg/testdiscoveryservice/testdiscovery_test.go
  pkg/testexecutionservice/testexecution.go
  pkg/testexecutionservice/testexecution_test.go
  pkg/utils/utils.go
  pkg/zstd/zstd_test.go
  testutils/mocks/Reader.go
Labels: release:patch

#198 added support for docker volumes
  .vscode/settings.json
  cmd/synapse/bin.go
  config/parse.go
  pkg/core/runner.go
  pkg/core/secrets.go
  pkg/cron/setup.go
  pkg/errs/synapse.go
  pkg/global/synapseconstants.go
  pkg/proxyserver/setup.go
  pkg/runner/docker/config.go
  pkg/runner/docker/docker.go
  pkg/runner/docker/docker_test.go
  pkg/secrets/secrets.go
  pkg/secrets/secrets_test.go
  pkg/synapse/synapse.go
Labels: release:minor

#203 [Feature]: Aborting jobs on synapse
  pkg/core/runner.go
  pkg/core/wsproto.go
  pkg/runner/docker/docker.go
  pkg/synapse/synapse.go
Labels: enhancement, release:minor
